[NAE-1813] Field id as path variable in TaskController
netgrif/application-engine pull request #166
Opened 2023-01-18 12:26 UTC by renczesstefan

# Description

Added base64 decoding for file field ID.

Fixes [NAE-1813]

## Dependencies

No new dependencies were introduced

### Third party dependencies

No new dependencies were introduced

### Blocking Pull requests

There are no dependencies on other PR

## How Has Been This Tested?

This was tested manually and with unit tests.

### Test Configuration

| Name                | Tested on |
|---------------------| --------- |
| OS                  |   macOS Ventura 13.1     |
| Runtime             |  Java 11        |
| Dependency Manager  |  Maven 3.8.4         |
| Framework version   |  Spring Boot 2.6.2        |
| Run parameters      |           |
| Other configuration |           |

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My changes have been checked, personally or remotely, with @mazarijuraj 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have resolved all conflicts with the target branch of the PR
- [x] I have updated and synced my code with the target branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes:
    - [ ] Lint test
    - [ ] Unit tests
    - [ ] Integration tests
- [x] I have checked my contribution with code analysis tools:
    - [x] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_application-engine)
    - [x] [Snyk](https://app.snyk.io/org/netgrif/project/ea82b3b8-658d-41f5-89a7-76cd600da01f)
- [x] I have made corresponding changes to the documentation:
    - [x] Developer documentation
    - [x] User Guides
    - [x] Migration Guides

2023-01-23 09:44 UTC, mazarijuraj reviewed
Not the best solution but if 6.3.0 needs to be released soon this will work.

2023-02-01 16:25 UTC, machacjozef requested changes

2023-02-01 16:25 UTC, machacjozef commented on src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
> +    public EntityModel<EventOutcomeWithMessage> saveFiles(@PathVariable("id") String taskId, @RequestPart(value = "data") FileFieldRequest requestBody, @RequestPart(value = "files") MultipartFile[] m
Missing annotation @Override

2023-02-02 08:54 UTC, renczesstefan commented on src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
> +    public EntityModel<EventOutcomeWithMessage> saveFiles(@PathVariable("id") String taskId, @RequestPart(value = "data") FileFieldRequest requestBody, @RequestPart(value = "files") MultipartFile[] m
Done

2024-03-11 11:14 UTC, Kovy95 approved these changes

2024-03-11 11:44 UTC, minop approved these changes

2024-03-11 16:32 UTC, tuplle approved these changes

2024-03-12 12:21 UTC, machacjozef approved these changes

2024-03-12 13:00 UTC, merged