[NAE-1952] Fix Loading Issue for Duplicate TaskRef Entries
netgrif/application-engine pull request #249
Opened 2024-03-05 14:41 UTC by Kovy95

# Description

- checking if the task ID isn't the displaying task ID

Fixes [NAE-1952]

## Dependencies

none

### Third party dependencies

No new dependencies were introduced

### Blocking Pull requests

There are no dependencies on other PR

## How Has Been This Tested?
manually

### Test Configuration

| Name                | Tested on |
|---------------------| --------- |
| OS                  |     Linux Mint 20      |
| Runtime             |     Java 11      |
| Dependency Manager  |      Maven 3.8.4     |
| Framework version   |     SpringBoot 2.6.2      |
| Run parameters      |           |
| Other configuration |           |

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes have been checked, personally or remotely, with @...
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have resolved all conflicts with the target branch of the PR
- [ ] I have updated and synced my code with the target branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes:
    - [ ] Lint test
    - [ ] Unit tests
    - [ ] Integration tests
- [ ] I have checked my contribution with code analysis tools:
    - [ ] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_application-engine)
    - [ ] [Snyk](https://app.snyk.io/org/netgrif/project/ea82b3b8-658d-41f5-89a7-76cd600da01f)
- [ ] I have made corresponding changes to the documentation:
    - [ ] Developer documentation
    - [ ] User Guides
    - [ ] Migration Guides

2024-05-21 11:36 UTC, renczesstefan approved these changes

2024-05-21 11:47 UTC, machacjozef commented on src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
> +        value.forEach(taskId -> {
if (taskIds.contains(restrictedTaskId)) {

2024-05-21 11:51 UTC, mazarijuraj commented on src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
> +            if (taskId.equals(restrictedTaskId)) {
Can `taskId` be `null`?

2024-05-21 11:55 UTC, minop requested changes
I am unsure, what the problem is.

The title/description of the jira issue imply, that the problem is adding the same task to a task ref twice.
The error message implies that the check is attempting to prevent a task reference loop.
The implementation changes suggest, only a direct reference loop is prevented (task contains a task ref which references the host task).

What is the problem? Why is this the solution?

2024-05-21 11:55 UTC, minop commented on src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
> +        value.forEach(taskId -> {
can be simplified to `if(value.contains(restrictedTaskId))`

2024-05-21 11:55 UTC, minop commented on src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
> +                throw new IllegalArgumentException(String.format("Task with id '%s' cannot be added to task ref, since it is an task which displaying task ref", restrictedTaskId));
possibly `"Task with id '%s' cannot be added to task ref, since it is a task which is displaying task ref"`.

2024-05-21 11:55 UTC, minop commented on src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
>                  // TODO 29.9.2020: validate task ref value? is such feature desired?
remove TODO?

2024-09-19 13:54 UTC, tuplle approved these changes

2024-09-25 09:07 UTC, renczesstefan approved these changes

2024-09-25 10:59 UTC, machacjozef approved these changes

2024-09-25 12:16 UTC, merged