[NAE-1477] New pdfgeneration action in actionDelegate
netgrif/application-engine pull request #39
Opened 2022-04-11 06:29 UTC by renczesstefan

# Description

Implemented new function for PDF generation into ActionDelegate.

Implements [NAE-1477]

## Dependencies

No new dependencies were introduced.

### Third party dependencies

No new dependencies were introduced.

### Blocking Pull requests

There are no dependencies on other PR.

## How Has Been This Tested?

This was tested manually and running the unit tests for PDF generator.

### Test Configuration

Netgrif Backend PR Config
| Name                | Tested on |
|---------------------| --------- |
| OS                  |   macOS Monterey 12.2.1        |
| Runtime             |  Java 11        |
| Dependency Manager  |  Maven 3.8.4         |
| Framework version   |  Spring Boot 2.6.2        |
| Run parameters      |           |
| Other configuration |           |

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes have been checked, personally or remotely, with @petrovicLubos 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have resolved all conflicts with the target branch of the PR
- [x] I have updated and synced my code with the target branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes:
    - [ ] Lint test
    - [ ] Unit tests
    - [ ] Integration tests
- [ ] I have checked my contribution with code analysis tools:
    - [ ] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_application-engine)
    - [ ] [Snyk](https://app.snyk.io/org/netgrif/project/ea82b3b8-658d-41f5-89a7-76cd600da01f)
- [x] I have made corresponding changes to the documentation:
    - [x] Developer documentation
    - [x] User Guides
    - [x] Migration Guides

2022-04-11 15:28 UTC, minop requested changes

2022-04-11 15:28 UTC, minop commented on src/test/groovy/com/netgrif/application/engine/pdf/service/PdfGeneratorTest.groovy
> +    void testingCustomFunction() {
the test has no assertions

2022-04-25 13:29 UTC, mladoniczky submitted a review, later dismissed

2022-04-26 08:06 UTC, minop approved these changes

2022-04-26 08:06 UTC, minop commented on src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
> +    void generatePdf(String transitionId, String fileFieldId) {
how does this change relate to the signature changes made in PR #40 ?

2022-05-16 12:28 UTC, mladoniczky approved these changes

2022-05-16 12:28 UTC, merged