[NAE-1049] Case name doesn't change
netgrif/application-engine pull request #46
Opened 2022-04-13 13:54 UTC by RudeBoyxX

# Description

 Added functionality to set task attributes caseTitle and caseColor
 Added task service method to return each Task by case id
 Added "refresh" of tasks on pre event actions
 Added test and test Petri net

Fixes [NAE-1049]

## Dependencies

None

### Third party dependencies

No new dependencies were introduced

### Blocking Pull requests

There are no dependencies on other PR

## How Has Been This Tested?

Tested on newly added Petri net (case_name_change_test.xml) manually in application and in written test

- [case_name_change_test.xml](https://github.com/netgrif/application-engine/blob/NAE-1049/src/test/resources/case_name_change_test.xml)
- [ChangeCasePropertyTest.groovy](https://github.com/netgrif/application-engine/blob/NAE-1049/src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/ChangeCasePropertyTest.groovy)

### Test Configuration

| Name                | Tested on |
|---------------------| --------- |
| OS                  |   Windows 11        |
| Runtime             |  Java 11        |
| Dependency Manager  |  Maven 3.8.4         |
| Framework version   |  Spring Boot 2.6.2        |
| Run parameters      |           |
| Other configuration |           |

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes have been checked, personally or remotely, with @timbez @machacjozef 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have resolved all conflicts with the target branch of the PR
- [x] I have updated and synced my code with the target branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes:
    - [ ] Lint test
    - [ ] Unit tests
    - [ ] Integration tests
- [ ] I have checked my contribution with code analysis tools:
    - [ ] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_application-engine)
    - [ ] [Snyk](https://app.snyk.io/org/netgrif/project/ea82b3b8-658d-41f5-89a7-76cd600da01f)
- [x] I have made corresponding changes to the documentation:
    - [x] Developer documentation
    - [x] User Guides
    - [x] Migration Guides

2022-04-19 10:47 UTC, minop approved these changes

2022-04-25 13:57 UTC, mladoniczky requested changes

2022-04-25 13:57 UTC, mladoniczky commented on src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
> +                    taskService.save(task)
It's better to call save on the whole list of tasks than to every single one separately.

2022-04-26 08:10 UTC, minop commented on src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
> +        tasks.forEach(task -> elasticTaskService.index(this.taskMappingService.transform(task)));
does a bulk elastic index method exist? I have a feeling something like that was implemented at some point.

2022-05-16 13:11 UTC, mladoniczky approved these changes

2022-05-18 13:17 UTC, tuplle commented on src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
> +        tasks.forEach(task -> elasticTaskService.index(this.taskMappingService.transform(task)));
Used `ElasticTaskService` does not have a method for bulk indexing of tasks. It is surely space for improvement.

2022-05-18 13:18 UTC, merged