NAE-1623 - few actions api functions refactored plus a few functions added
netgrif/application-engine pull request #49
Opened 2022-04-27 08:29 UTC by petrovicLubos

NAE-1623 - few actions API functions refactored plus a few functions added

2022-04-27 12:18 UTC, minop requested changes

2022-04-27 12:18 UTC, minop commented on src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
> +             behavior(field, trans)
duplicate code with the above implementation

2022-04-27 12:18 UTC, minop commented on src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
> +    void generatePDF(String transitionId, FileField fileField) {
how does the introduction of these methods relate to the changes made to these methods in PRs #39 and #40 ?

2022-04-27 12:18 UTC, minop commented on src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
> +            log.error("Cannot find user with email [" + email + "]")
the error message does not correspond to the implementation

2022-04-29 12:03 UTC, machacjozef commented
### Please edit:

- [ ] Title
- [ ] Description
- [ ] Change commit message
- [ ] Fix Test

2022-04-29 12:04 UTC, machacjozef requested changes
### Please make changes:

- [ ] edit Title
- [ ] edit Description
- [ ] Change commit message
- [x] Fix Test

2022-04-29 12:39 UTC, RudeBoyxX commented on src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
> +         on: { Transition trans ->
make method improvements are part of https://netgrif.atlassian.net/browse/NAE-1622 (currently in progress)

2022-04-29 12:51 UTC, minop commented on src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
> +    void generatePDF(String transitionId, FileField fileField) {
@renczesstefan informed me that he will resolve conflicted changes made to these methods once the related PRs are ready to merge

2022-05-02 11:40 UTC, minop requested changes

2022-05-02 11:40 UTC, minop commented on src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
> -        }]
the `]` bracket is missing

2022-05-02 13:09 UTC, minop approved these changes

2022-05-16 13:18 UTC, mladoniczky approved these changes

2022-05-16 13:21 UTC, machacjozef approved these changes

2022-05-18 12:47 UTC, minop requested changes

2022-05-18 12:47 UTC, minop commented on src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
> +    void generatePDF(String transitionId, FileField fileField) {
this method should probably call the `generatePDF(String, FileField, List<String>)` method or make use of groovy default parameter values to reduce duplication

2022-05-18 13:56 UTC, minop submitted a review, later dismissed

2022-05-25 08:40 UTC, machacjozef approved these changes

2022-05-25 08:40 UTC, mladoniczky approved these changes

2022-05-25 10:23 UTC, minop submitted a review, later dismissed

2022-05-26 13:36 UTC, mladoniczky approved these changes

2022-05-26 14:05 UTC, machacjozef approved these changes

2022-05-26 14:08 UTC, merged