[NAE-1627] LDAP Groups resolving and mapping
netgrif/application-engine pull request #58
Opened 2022-05-13 11:27 UTC by machacjozef

# Description

Implements [NAE-1627]

## Dependencies

### Third party dependencies

 No new dependencies were introduced

### Blocking Pull requests

Depends on #(PR id) (@machacjozef edit)

## How Has Been This Tested?

This was tested manually and using unit tests.

manually + new test

- NetgrifLdapAuthenticationProviderTest [NetgrifLdapAuthenticationProviderTest](https://github.com/netgrif/application-engine/blob/NAE-1627/src/test/java/com/netgrif/application/engine/configuration/authentication/providers/NetgrifLdapAuthenticationProviderTest.java)

### Test Configuration

| Name                | Tested on |
|---------------------| --------- |
| OS                  |   Linux Mint 20.3        |
| Runtime             |  Java 11        |
| Dependency Manager  |  Maven 3.8.4         |
| Framework version   |  Spring Boot 2.6.7      |
| Run parameters      |           |
| Other configuration |           |

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes have been checked, personally or remotely, with @timbez @mladoniczky @petrovicLubos 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have resolved all conflicts with the target branch of the PR
- [x] I have updated and synced my code with the target branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes:
    - [x] Lint test
    - [x] Unit tests
    - [x] Integration tests
- [x] I have checked my contribution with code analysis tools:
    - [x] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_application-engine)
    - [x] [Snyk](https://app.snyk.io/org/netgrif/project/ea82b3b8-658d-41f5-89a7-76cd600da01f)
- [x] I have made corresponding changes to the documentation:
    - [x] Developer documentation
    - [x] User Guides
    - [x] Migration Guides

2022-05-25 09:01 UTC, mladoniczky requested changes

2022-05-25 09:01 UTC, tuplle commented on src/main/java/com/netgrif/application/engine/ldap/domain/LdapGroup.java
> +    @Id
Why is this LDAP Id annotation on ObjectId which is MongoDB id object?
If it is object for MongoDB the class should have @Document annotation.

2022-05-25 09:01 UTC, tuplle commented on src/main/java/com/netgrif/application/engine/ldap/service/LdapGroupRefService.java
> +    public void addRoleToLdapGroup(String groupDn, Set<String> requestedRolesIds, LoggedUser loggedUser) {
This method is setting a whole new set of process roles to a group, so the method's name is not correct.

2022-05-26 11:10 UTC, machacjozef commented on src/main/java/com/netgrif/application/engine/ldap/domain/LdapGroup.java
> +    @Id
Done

2022-05-26 11:10 UTC, machacjozef commented on src/main/java/com/netgrif/application/engine/ldap/service/LdapGroupRefService.java
> +    public void addRoleToLdapGroup(String groupDn, Set<String> requestedRolesIds, LoggedUser loggedUser) {
Done

2022-05-26 13:28 UTC, mladoniczky approved these changes

2022-05-26 13:29 UTC, merged