[NAE-1631] Process download in workflow view
netgrif/application-engine pull request #61
Opened 2022-05-17 13:11 UTC by Daniell7

# Description

Add fix to set content to generated xml file from imported net

Implements [NAE-1631]

## Dependencies

No new dependencies

### Third party dependencies

No new dependencies were introduced

### Blocking Pull requests

There are no dependencies on other PR

## How Has Been This Tested?

Assisted testing + manual testing

### Test Configuration

| Name                | Tested on |
|---------------------| --------- |
| OS                  | Windows 10 |
| Runtime             | Java 11 |
| Dependency Manager  | Maven 3.8.1 |
| Framework version   | Spring Boot 2.6.2 |
| Run parameters      |           |
| Other configuration |           |

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes have been checked, personally or remotely, with @...
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have resolved all conflicts with the target branch of the PR
- [ ] I have updated and synced my code with the target branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes:
    - [ ] Lint test
    - [ ] Unit tests
    - [ ] Integration tests
- [ ] I have checked my contribution with code analysis tools:
    - [ ] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_application-engine)
    - [ ] [Snyk](https://app.snyk.io/org/netgrif/project/ea82b3b8-658d-41f5-89a7-76cd600da01f)
- [ ] I have made corresponding changes to the documentation:
    - [ ] Developer documentation
    - [ ] User Guides
    - [ ] Migration Guides

2022-06-21 11:49 UTC, minop submitted a review, later dismissed

2022-06-21 11:51 UTC, minop commented
> Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=netgrif_application-engine&pullRequest=61)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=netgrif_application-engine&pullRequest=61&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=netgrif_application-engine&pullRequest=61&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=netgrif_application-engine&pullRequest=61&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=netgrif_application-engine&pullRequest=61&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=netgrif_application-engine&pullRequest=61&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=netgrif_application-engine&pullRequest=61&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=netgrif_application-engine&pullRequest=61&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=netgrif_application-engine&pullRequest=61&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=netgrif_application-engine&pullRequest=61&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=netgrif_application-engine&pullRequest=61&resolved=false&types=CODE_SMELL) [![B](https://camo.githubusercontent.com/ee7f8cac547e3e28ad7e683c451c8caf2f19d70bc37d6bcba574dac8ff86d194/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f422d313670782e706e67)](https://sonarcloud.io/project/issues?id=netgrif_application-engine&pullRequest=61&resolved=false&types=CODE_SMELL) [2 Code Smells](https://sonarcloud.io/project/issues?id=netgrif_application-engine&pullRequest=61&resolved=false&types=CODE_SMELL)
> 
> [![100.0%](https://camo.githubusercontent.com/7dbca5aee76a2476a5206e509c0f0a9a09e855e417f428b43302198d262ed98c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f3130302d313670782e706e67)](https://sonarcloud.io/component_measures?id=netgrif_application-engine&pullRequest=61&metric=new_coverage&view=list) [100.0% Coverage](https://sonarcloud.io/component_measures?id=netgrif_application-engine&pullRequest=61&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=netgrif_application-engine&pullRequest=61&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=netgrif_application-engine&pullRequest=61&metric=new_duplicated_lines_density&view=list)

for some reason I cannot open the sonar report for code smells. But please check what is going on with them

2022-06-21 14:24 UTC, camperko submitted a review, later dismissed

2022-08-26 08:26 UTC, mladoniczky requested changes

2022-08-26 08:26 UTC, mladoniczky commented on src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
> +        Optional<PetriNet> imported = getImporter().importPetriNet(xmlCopy1);
Why is the imported process file 4 times in RAM (like xmlFile, baos, xmlCopy1, xmlCopy2)?

2022-08-30 15:08 UTC, machacjozef approved these changes

2022-09-05 14:24 UTC, mladoniczky approved these changes

2022-09-05 16:14 UTC, merged